FROM  quay.io/biocontainers/cellrank:1.5.1--pyhdfd78af_0

LABEL authors="alex.thiery@crick.ac.uk" \
      description="Docker image containing cellrank and jupyter"

# Install notebook
RUN pip install notebook