FROM  quay.io/biocontainers/scvelo:0.2.4--pyhdfd78af_0

LABEL authors="alex.thiery@crick.ac.uk" \
      description="Docker image containing scvelo and jupyter"

# Install notebook
RUN pip install notebook
    